# Generated by Django 5.2.1 on 2025-06-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
